spring.application.name=gateway


server.port=8051
jwt.secret=814b9fa5df51e0cbb0059bbee01f0b2c91f3211e4715ffe1370147047ec4e57bf7a5f89638677afdd1456f3e37db36c8ab55229a38f89002e9e1b97a28370486

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8050/eureka/}

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=profile-service
spring.cloud.gateway.routes[0].uri=lb://PROFILE-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

spring.cloud.gateway.routes[1].id=movie-service
spring.cloud.gateway.routes[1].uri=lb://MOVIE-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/movies/**